<a href="https://colab.research.google.com/github/ayobami4/TechCrush-Cohort-9_AI-ML/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2

## Pandas

In [1]:
# Importing the pandas library
import pandas as pd

### Hands-on Practice

* Create a dataframe that has column names of food, class of the food, and price using a list of lists.  
* Rename the index of the created table

In [2]:
# Creating a dataframe that has column names of food, class of the food, and price using a list of lists
# Defining a list
my_list = [
    ['Beans', 'Protein', 200],
    ['Bread', 'Carbonhydrate', 300],
    ['Rice','Carbohydrate', 400]
]

# Creating a dataframe
my_df = pd.DataFrame(my_list, columns=['Food', 'Class', 'Price'])

# Viewing the dataframe
my_df

    Food          Class  Price
0  Beans        Protein    200
1  Bread  Carbonhydrate    300
2   Rice   Carbohydrate    400

In [3]:
# Renaming the index
my_df.index = ['a', 'b', 'c']

# Verifying the affected dataframe
my_df

    Food          Class  Price
a  Beans        Protein    200
b  Bread  Carbonhydrate    300
c   Rice   Carbohydrate    400

## NumPy

In [4]:
# Importing the numpy library
import numpy as np

**Hands-on Practice**

1. Create a 3 x 4 NumPy array with random integers between 1 and 100. Display the array.
2. From the array created in Question 1, extract the following: (a) the first two rows. (b) the last 3 columns (c) All even numbers in the array.
3. Perform the following transformation on the array created in Question 1: (a) reshape the array into a 3D (2, 2, 3) array. (b) Now you flatten the reshaped array back to 1D.
4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.
5. Perform matrix multiplication between a 3x4 matrix of random integers (1-10) and a 4x3 matrix of random integers (1-10).
6. Create a function that takes a 2D NumPy array as input and then returns a new array where all even numbers are squared and all odds numbers are replaced by -1

In [5]:
# Creating a 3 x 4 NumPy array with random integers between 1 and 100
my_array = np.random.randint(1, 101, (3, 4))

# Displaying the array
print(my_array)

[[61 61 66 13]
 [55 43 20 42]
 [77 82 11 41]]

In [6]:
# Extracting the first two rows
first_two_rows = my_array[:2, :]
print(f'The first two rows: \n {first_two_rows} \n')

# Extracting the last 3 columns
last_three_columns = my_array[:, -3:]
print(f'The last 3 columns: \n {last_three_columns} \n')

# Extracting all even numbers in the array
even_numbers = my_array[my_array % 2 == 0]
print(f'All the even numbers: \n {even_numbers}')

The first two rows:
 [[61 61 66 13]
 [55 43 20 42]]

The last 3 columns:
 [[61 66 13]
 [43 20 42]
 [82 11 41]]

All the even numbers:
 [66 20 42 82]

In [7]:
# Reshaping the array into a 3D (2, 2, 3) array
reshaped_array = my_array.reshape(2, 2, 3)
print(f'Reshaped array: \n {reshaped_array} \n')

# Flattening the reshaped array back to 1D
flattened_array = reshaped_array.flatten()
print(f'Flattened array: \n {flattened_array}')

Reshaped array:
 [[[61 61 66]
  [13 55 43]]

 [[20 42 77]
  [82 11 41]]]

Flattened array:
 [61 61 66 13 55 43 20 42 77 82 11 41]

In [8]:
# Generating a 4x4 identity matrix
identity_matrix = np.eye(4)
print(f'Identity matrix: \n {identity_matrix} \n')

# Replacing the diagonal with numbers from 10 to 40, with a step of 10
diagonal_matrix = np.diag(np.arange(10, 41, 10))
print(f'Replaced diagonal: \n {diagonal_matrix}')

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Replaced diagonal:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

In [9]:
# Performing matrix multiplication between a 3x4 matrix of random integers (1-10) and a 4x3 matrix of random integers (1-10)
# Defining the matrix variables
matrix1 = np.random.randint(1, 11, (3, 4))
matrix2 = np.random.randint(1, 11, (4, 3))

# Performing multiplication between the two defined matrix variables
multiply = np.dot(matrix1, matrix2)

# Printing the result
print(f'Result: {multiply}')

Result: [[127 174 179]
 [114 206 189]
 [ 76 176 144]]

In [10]:
# Creating a function that takes a 2D NumPy array as input and then returns a new array where all even numbers are squared and all odds numbers are replaced by -1
def my_function(my_2darray):
  result = np.where(my_2darray % 2 == 0, my_2darray ** 2, -1)
  return result

# Defining a 2D NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Calling the function
my_function(my_array)

array([[-1,  4, -1],
       [16, -1, 36]])